### Numpy
- 데이터를 행렬로 표현
- 행렬 데이터 빠르게 계산을 해야 합니다.
- 행렬 데이터 생성, 수정, 계산등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 매트릭스

In [2]:
import numpy as np

In [11]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능

In [4]:
array = np.array([1, 2, 3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [6]:
array2 = np.array(
    [[1, 2, 3],
    [4, 5, 6]],
)
type(array2), array2

(numpy.ndarray,
 array([[1, 2, 3],
        [4, 5, 6]]))

In [10]:
array2, array2.ndim, array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [15]:
# 행렬의 모양(shape) 변경하기
array2.reshape(6), array2.reshape(2,3), array2.reshape(3, 2, 1), array2.reshape(3, 2),

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1],
         [2]],
 
        [[3],
         [4]],
 
        [[5],
         [6]]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [26]:
# 행렬 데이터의 선택 : offset index : masking

In [27]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array2[1][2], array2[1][:2], array2[1][::-1]

(6, array([4, 5]), array([6, 5, 4]))

In [25]:
array2[1, 2] # = array2[1][2]

6

In [30]:
# 데이터 수정

In [31]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [29]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
array2[1][2] = 10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [36]:
# 브로드 캐스팅
array2[0] = 0
array2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [37]:
array2[0] = [7, 8, 9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [42]:
# 조건으로 선택
idx = array2 > 7
idx

array([[False,  True,  True],
       [False, False,  True]])

In [41]:
array2[idx]

array([ 8,  9, 10])

In [43]:
array2[idx] = 100
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [48]:
array2.dtype

dtype('int32')

In [44]:
# 행렬 데이터의 생성 2

In [46]:
data = np.zeros((2, 3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
data.dtype

dtype('float64')

In [49]:
data2 = data.astype("int")
data2.dtype

dtype('int32')

In [50]:
data2

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
data = np.ones((2, 3, 2))
data

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [52]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [53]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [3]:
np.arange(3, 8, 2)

array([3, 5, 7])

In [1]:
np.arange(5, 10, 2)

array([5, 7, 9])