### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성 1. : ndarray, np.array(iterable)
- 행렬의 생성 2. : ones, zeros
- 행렬 데이터 선택 : array[x, y, z]
- 행렬 데이터 수정 : 
    - 행렬 데이터를 선택
    - =, > (값(scala, vector, matrix))
    - 브로드 캐스팅 개념
- arange : list 에서 쓰는 range : 결과가 ndarray 타입으로 출력


### quiz
- 100 ~ 130 까지 랜덤한 숫자를 가지는 8*8 행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환\
- 위의 조건에 맞지 않는 데이터는 랜덤하게 생성된 정수로 출력
- 랜덤한 행렬 데이터
```
datas = np.random.randint(100, 130, size=(8,8))
```
- 데이터 타입이 정수 -> 문자열 : ndarray.astype()

In [3]:
import numpy as np

In [5]:
datas = np.random.randint(100, 130, size=(8, 8))
datas

array([[109, 119, 120, 109, 128, 121, 126, 103],
       [104, 105, 120, 119, 107, 111, 107, 117],
       [115, 101, 103, 118, 124, 108, 123, 107],
       [104, 109, 103, 100, 101, 105, 118, 116],
       [107, 126, 119, 103, 101, 117, 124, 124],
       [105, 116, 122, 122, 113, 103, 118, 103],
       [127, 102, 109, 125, 129, 126, 121, 125],
       [112, 106, 128, 104, 106, 126, 103, 115]])

In [52]:
three = datas % 3 == 0
five = datas % 5 == 0
three_five = datas % (3*5) == 0

str_dats = datas.astype(str)
str_dats[three] = "fiz"
str_dats[five] = "buz"
str_dats[three_five] = "fbz"

str_dats

array([['109', '119', 'fbz', '109', '128', '121', 'fiz', '103'],
       ['104', 'fbz', 'fbz', '119', '107', 'fiz', '107', 'fiz'],
       ['buz', '101', '103', '118', '124', 'fiz', 'fiz', '107'],
       ['104', '109', '103', 'buz', '101', 'fbz', '118', '116'],
       ['107', 'fiz', '119', '103', '101', 'fiz', '124', '124'],
       ['fbz', '116', '122', '122', '113', '103', '118', '103'],
       ['127', 'fiz', '109', 'buz', 'fiz', 'fiz', '121', 'buz'],
       ['112', '106', '128', '104', '106', 'fiz', '103', 'buz']],
      dtype='<U11')

In [54]:
# 3의 배수, 5의 배수 , 15의 배수 위치값에 대한 T,F 매트릭스 생성
idx_3 = datas % 3 == 0
idx_5 = datas % 5 == 0
idx_15 = datas % 15 == 0

In [56]:
# 데이터의 타입을 str로 변환
result = datas.astype("str")
result

array([['109', '119', '120', '109', '128', '121', '126', '103'],
       ['104', '105', '120', '119', '107', '111', '107', '117'],
       ['115', '101', '103', '118', '124', '108', '123', '107'],
       ['104', '109', '103', '100', '101', '105', '118', '116'],
       ['107', '126', '119', '103', '101', '117', '124', '124'],
       ['105', '116', '122', '122', '113', '103', '118', '103'],
       ['127', '102', '109', '125', '129', '126', '121', '125'],
       ['112', '106', '128', '104', '106', '126', '103', '115']],
      dtype='<U11')

In [57]:
# T,F 매트릭스를 이용하여 특정조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입
result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "fbz"

In [58]:
result

array([['109', '119', 'fbz', '109', '128', '121', 'fiz', '103'],
       ['104', 'fbz', 'fbz', '119', '107', 'fiz', '107', 'fiz'],
       ['buz', '101', '103', '118', '124', 'fiz', 'fiz', '107'],
       ['104', '109', '103', 'buz', '101', 'fbz', '118', '116'],
       ['107', 'fiz', '119', '103', '101', 'fiz', '124', '124'],
       ['fbz', '116', '122', '122', '113', '103', '118', '103'],
       ['127', 'fiz', '109', 'buz', 'fiz', 'fiz', '121', 'buz'],
       ['112', '106', '128', '104', '106', 'fiz', '103', 'buz']],
      dtype='<U11')

### Quiz2
- 1 ~ 20 까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최댓값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수
```
np.min(ndarray), np.max(ndarray)
```

In [61]:
datas = np.random.randint(1, 20, size=(5, 5))
datas

array([[ 5,  5, 13, 15, 14],
       [ 3,  1,  4, 14,  7],
       [ 3, 13, 12,  9,  8],
       [ 4, 19,  1, 18,  1],
       [15,  1,  2,  7, 12]])

In [64]:
result = datas.astype(str)
result

array([['5', '5', '13', '15', '14'],
       ['3', '1', '4', '14', '7'],
       ['3', '13', '12', '9', '8'],
       ['4', '19', '1', '18', '1'],
       ['15', '1', '2', '7', '12']], dtype='<U11')

In [70]:
# 최솟값, 최댓값 T,F 매트릭스 생성
min = datas == np.min(datas)
max = datas == np.max(datas)

In [72]:
result[min] = "MIN"
result[max] = "MAX"
result

array([['5', '5', '13', '15', '14'],
       ['3', 'MIN', '4', '14', '7'],
       ['3', '13', '12', '9', '8'],
       ['4', 'MAX', 'MIN', '18', 'MIN'],
       ['15', 'MIN', '2', '7', '12']], dtype='<U11')

### 1. linspace, logspace 함수
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [74]:
# linspace(start, end, div)
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [75]:
# logspace(start, end, div)
# log10(x1)=2, log10(x2)=3, log10(x3)=4
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

In [76]:
# 30세에 연봉이 $100000 이고, 60세의 연봉이 $1000000 일때
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세, 50세의 연봉을 출력

In [77]:
age_30 = 100000
age_60 = 1000000

In [78]:
np.linspace(age_30, age_60, 4)  # 30, 40,50, 60 4등분

array([ 100000.,  400000.,  700000., 1000000.])

In [83]:
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

###  2.  numpy random
- seed : 랜덤값의 설정값
- rand : 균등분포로 난수를 발생
- randn : 정규분포로 난수를 발생 (**정규분포를 더 많이 씀**)
- randint : 균등분포로 정수값을 발생
- suffle : 행렬 데이터를 섞어 준다.
- choice : 특정 확률로 데이터를 선택

In [85]:
# seed # 객체를 바꿔주는 느낌
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [4]:
ra = np.random
ra.seed(1)
result = ra.randint(1, 100, 10)
result

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [104]:
# rand 0~1균등분포
np.random.rand(10)

array([0.57027421, 0.91671461, 0.70226424, 0.50121645, 0.50608683,
       0.21882079, 0.00466352, 0.41783624, 0.56337611, 0.87656187])

In [20]:
# randn 0과 가깝게 정규분포로 출력
np.random.randn(30)

array([ 0.86888616,  0.75041164,  0.52946532,  0.13770121,  0.07782113,
        0.61838026,  0.23249456,  0.68255141, -0.31011677, -2.43483776,
        1.0388246 ,  2.18697965,  0.44136444, -0.10015523, -0.13644474,
       -0.11905419,  0.01740941, -1.12201873, -0.51709446, -0.99702683,
        0.24879916, -0.29664115,  0.49521132, -0.17470316,  0.98633519,
        0.2135339 ,  2.19069973, -1.89636092, -0.64691669,  0.90148689])

In [21]:
# shuffle # 행렬의 순서만 바꿈
r = np.random.randint(1, 10, (3, 4))
r

array([[7, 5, 8, 7],
       [3, 6, 9, 7],
       [5, 3, 5, 1]])

In [22]:
# 값을 다 바꾸는게 아니라 리스트 순서를 바꿈
np.random.shuffle(r)
r

array([[3, 6, 9, 7],
       [5, 3, 5, 1],
       [7, 5, 8, 7]])

In [44]:
# 리스트를 한줄로 변경한뒤 셔플 후 다시 리스트 리쉐이프로 변경
r = r.reshape(12,1)
np.random.shuffle(r)
r = r.reshape(3,4)
r

array([[5, 1, 7, 6],
       [3, 7, 5, 8],
       [7, 3, 9, 5]])

In [46]:
# choice # p 합은 1이 되야함 p는 확률
# choice(0~range, size, p)
np.random.choice(5, 30, p=[0.1, 0, 0.4, 0.2, 0.3])

array([3, 3, 4, 2, 4, 4, 2, 2, 4, 3, 2, 2, 2, 2, 3, 4, 2, 4, 2, 4, 2, 2,
       2, 0, 2, 3, 4, 4, 2, 4])

In [47]:
# unique 유일한 값들을 뽑아줌
np.unique(r)

array([1, 3, 5, 6, 7, 8, 9])

In [53]:
# unique 옵션 사용

numbers, counts = np.unique(r, return_counts=True)
print(numbers)
print(counts)

[1 3 5 6 7 8 9]
[1 2 3 1 3 1 1]


### 3. 행렬 데이터의 결합
- concatenate

In [55]:
na1 = np.random.randint(10, size=(2, 3))
na2 = np.random.randint(10, size=(3, 2))
na3 = np.random.randint(10, size=(3, 3))

In [160]:
# 세로 결합 size = ( a * b) b의 갯수 같아야 세로 결합 가능
na1, na3

(array([[4, 8, 6],
        [8, 6, 4]]),
 array([[0, 2, 3],
        [0, 1, 1],
        [9, 6, 2]]))

In [161]:
np.concatenate((na1, na3))

array([[4, 8, 6],
       [8, 6, 4],
       [0, 2, 3],
       [0, 1, 1],
       [9, 6, 2]])

In [57]:
na2, na3

(array([[1, 3],
        [2, 6],
        [3, 6]]),
 array([[7, 2, 8],
        [0, 1, 8],
        [6, 0, 0]]))

In [58]:
# 가로 결합 axis : 축, size = (a * b) a값이 같아야 결합 가능
np.concatenate((na2, na3), axis=1)

array([[1, 3, 7, 2, 8],
       [2, 6, 0, 1, 8],
       [3, 6, 6, 0, 0]])

In [165]:
# c_, r_
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [166]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [167]:
# split, var, std, mean ...