### 선형회기 분석
- 프리미어리그 데이터(득점, 실정, 승점)
- 득점, 실점 -> 승점 예측하는 모델
- scikit-learn 패키지
    - 데이터 마이닝 및 데이터 분석, 모델을 위한 도구
    - 상업적으로 사용이 가능한 오픈소스

In [1]:
import pickle

# 선형회귀 모델
from sklearn import linear_model
# 학습 데이터와 테스트 데이터를 나눠주는 모듈
from sklearn.model_selection import train_test_split
# 모델을 평가해주는 모듈
from sklearn.metrics import mean_absolute_error

#### 분석 절차
1. 데이터 로드
1. 데이터 전처리 : 
    - 독립변수(sample data)와 종속변수(결과를 예측할 칼럼 변수) 를 나눠줌
    - 학습 데이터와 테스트 데이터를 나눠줌
1. 데이터 분석 : 선형회귀 모델
1. 성능 평가: MAE
1. 예측 코드 작성

In [2]:
# 1. 데이터 로드
p_df = pd.read_csv("datas/premierleague.csv")
p_df.tail(2)

name  gf  ga  points
18            Stoke City  35  68      33
19  West Bromwich Albion  31  56      31

In [9]:
# 2. 데이터 전처리 
# 2 - 1. 독립변수, 종속변수 나누기 

df_x = p_df[["gf", "ga"]] # 독립 변수
df_y = p_df[["points"]]   # 종속 변수

In [11]:
# 2. 데이터 전처리
# 2 - 2. 학습 데이터, 테스트 데이터로 나누기 

# test_size=0.3 :  30%는 테스트 데이터, 70%는 트레인 데이터
# random_state=1 : 랜덤시드와 같은역할 
train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.3, random_state=1)

In [44]:
len(train_x)

14

In [15]:
# 3. 데이터 분석 : 선형회귀 모델
model = linear_model.LinearRegression()

In [16]:
# 모델 피팅
model.fit(train_x, train_y)

LinearRegression()

In [18]:
# 4. 성능 평가 MAE

In [19]:
pred_y = model.predict(test_x)
pred_y

array([[80.88065736],
       [40.79778662],
       [50.9467527 ],
       [46.31419247],
       [76.04209484],
       [40.23228639]])

In [22]:
test_y["points"].values

array([75, 36, 54, 44, 77, 40], dtype=int64)

In [25]:
# 모양 맞추기 ndarray.flatten()
pred_y = np.around(pred_y.flatten()).astype(int)
pred_y

array([81, 41, 51, 46, 76, 40])

In [27]:
mae = mean_absolute_error(test_y, pred_y)
round(mae, 2)

2.83

In [28]:
# 5. 예측 함수
def make_df(gf, ga) :
    return pd.DataFrame({"gf" : [gf], "ga" : [ga]})

In [35]:
gf, ga = 80, 30
result = int( model.predict(make_df(gf, ga)).flatten()[0] )
result

83

In [36]:
p_df.head()

name   gf  ga  points
0    Manchester City  106  27     100
1  Manchester United   68  28      81
2  Tottenham Hotspur   74  36      77
3          Liverpool   84  38      75
4            Chelsea   62  38      70

In [38]:
# pickle 파일로 모델 저장하기
with open ("datas/p_model.pkl", "wb") as f :
    pickle.dump(model, f)

In [41]:
# 파일 불러오기
with open ("datas/p_model.pkl", "rb") as f :
    load_model = pickle.load(f)

In [42]:
gf, ga = 55, 11
result = int( load_model.predict(make_df(gf, ga)).flatten()[0] )
result

80