### summary
- 프리미어리그 상관계수
- 02_numpy_2 ~ 03_pandas_1

In [26]:
# csv 파일 읽기

df = pd.read_csv("datas/premierleague.csv")
df.tail()

name  gf  ga  points
15     Huddersfield Town  28  58      37
16           Southampton  37  56      36
17          Swansea City  28  56      33
18            Stoke City  35  68      33
19  West Bromwich Albion  31  56      31

In [29]:
# 데이터 리스트 추출
gf = np.array(df["gf"])
ga = np.array(df["ga"])
points = np.array(df["points"])

In [30]:
# 공분산 ** 2 : 상관계수
gf_points = np.corrcoef(gf, points)[0][1] ** 2
ga_points = np.corrcoef(ga, points)[0][1] ** 2

In [31]:
round(gf_points, 2), round(ga_points, 2)  # 득점이 포인트와 상관계수가 더 높음

(0.87, 0.76)

### quiz
- 100 ~ 130 까지 랜덤한 숫자를 가지는 8*8 행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환
- 위의 조건에 맞지 않는 데이터는 랜덤하게 생성된 정수로 출력
- 랜덤한 행렬 데이터
```
datas = np.random.randint(100, 130, size=(8,8))
```
- 데이터 타입이 정수 -> 문자열 : ndarray.astype()

In [1]:
datas = np.random.randint(100, 130, (8, 8))
datas

array([[104, 103, 117, 127, 104, 113, 114, 111],
       [111, 102, 104, 108, 126, 118, 124, 115],
       [101, 102, 110, 118, 121, 124, 106, 126],
       [120, 115, 107, 111, 105, 126, 120, 107],
       [107, 124, 106, 129, 102, 117, 123, 121],
       [110, 106, 127, 112, 120, 124, 116, 103],
       [105, 108, 117, 125, 128, 111, 106, 125],
       [111, 116, 120, 119, 121, 112, 124, 124]])

In [3]:
index_3 = datas % 3 == 0
index_5 = datas % 5 == 0
index_15 = datas % 15 == 0

In [7]:
result = datas.astype(str)

result[index_3] = "fiz"
result[index_5] = "buz"
result[index_15] = "fbz"

result

array([['104', '103', 'fiz', '127', '104', '113', 'fiz', 'fiz'],
       ['fiz', 'fiz', '104', 'fiz', 'fiz', '118', '124', 'buz'],
       ['101', 'fiz', 'buz', '118', '121', '124', '106', 'fiz'],
       ['fbz', 'buz', '107', 'fiz', 'fbz', 'fiz', 'fbz', '107'],
       ['107', '124', '106', 'fiz', 'fiz', 'fiz', 'fiz', '121'],
       ['buz', '106', '127', '112', 'fbz', '124', '116', '103'],
       ['fbz', 'fiz', 'fiz', 'buz', '128', 'fiz', '106', 'buz'],
       ['fiz', '116', 'fbz', '119', '121', '112', '124', '124']],
      dtype='<U11')

### Quiz2
- 1 ~ 20 까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최댓값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수
```
np.min(ndarray), np.max(ndarray)
```

In [47]:
datas = np.random.randint(1, 20, (5, 5))
datas

array([[ 9, 14,  7, 16, 11],
       [ 8, 10,  9,  3,  3],
       [15,  4,  9,  6,  8],
       [19,  8, 11, 17,  7],
       [19,  3, 18,  7,  6]])

In [52]:
#최솟값, 최댓값
min = np.min(datas)
max = np.max(datas)

min, max

(3, 19)

In [53]:
min_m = datas == min
max_m = datas == max

min_m, max_m

(array([[False, False, False, False, False],
        [False, False, False,  True,  True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True, False, False, False]]),
 array([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [ True, False, False, False, False],
        [ True, False, False, False, False]]))

In [54]:
str_datas = datas.astype(str)
str_datas

array([['9', '14', '7', '16', '11'],
       ['8', '10', '9', '3', '3'],
       ['15', '4', '9', '6', '8'],
       ['19', '8', '11', '17', '7'],
       ['19', '3', '18', '7', '6']], dtype='<U11')

In [55]:
str_datas[min_m] = "MIN"
str_datas[max_m] = "MAX"

str_datas

array([['9', '14', '7', '16', '11'],
       ['8', '10', '9', 'MIN', 'MIN'],
       ['15', '4', '9', '6', '8'],
       ['MAX', '8', '11', '17', '7'],
       ['MAX', 'MIN', '18', '7', '6']], dtype='<U11')

## Pandas 

1. Series : index와 value로 이루어진 데이터 타입
1. DataFrame : index, column, value로 이루어진 데이터 타입

In [57]:
data = pd.Series(np.random.randint(10, size=5))
data

0    8
1    4
2    6
3    7
4    3
dtype: int32

In [61]:
# index 설정
data = pd.Series(np.random.randint(10, size=5), index=list("ABCDE"))
data = pd.Series(np.random.randint(10, size=5), index=list("ABCDE"))

data

A    5
B    6
C    0
D    1
E    6
dtype: int32

In [63]:
data.index, data.values

(Index(['A', 'B', 'C', 'D', 'E'], dtype='object'), array([5, 6, 0, 1, 6]))

In [67]:
data["B"], data.B

(6, 6)

In [69]:
data.B = 10
data

A     5
B    10
C     0
D     1
E     6
dtype: int32

In [70]:
data * 10

A     50
B    100
C      0
D     10
E     60
dtype: int32

In [74]:
data[list("BE")], data[["B","E"]]

(B    10
 E     6
 dtype: int32,
 B    10
 E     6
 dtype: int32)

In [76]:
data[:2], data[::-1]

(A     5
 B    10
 dtype: int32,
 E     6
 D     1
 C     0
 B    10
 A     5
 dtype: int32)

In [89]:
data

A     5
B    10
C     0
D     1
E     6
dtype: int32

In [90]:
data2 = pd.Series({"D" : 3, "E" : 5, "F": 6})
data2

D    3
E    5
F    6
dtype: int64

In [91]:
result = data + data2 # 같은 인덱스끼리만 연산이 된다.
result

A     NaN
B     NaN
C     NaN
D     4.0
E    11.0
F     NaN
dtype: float64

In [93]:
result[result == 4] = 3
result

A     NaN
B     NaN
C     NaN
D     3.0
E    11.0
F     NaN
dtype: float64

In [94]:
result[result.isnull()] = data
result

A     5.0
B    10.0
C     0.0
D     3.0
E    11.0
F     NaN
dtype: float64

In [95]:
result[result.isnull()] = data2
result

A     5.0
B    10.0
C     0.0
D     3.0
E    11.0
F     6.0
dtype: float64

### 2. DataFrame
- 데이터 프레임은 여러개의 Series로 구성
- 같은 컬럼에 있는 value값은 같은 데이터 타입만 갖는다.

In [ ]:
# 데이터 프레임 생성 1 : 딕셔너리의 리스트

In [99]:
# 칼럼형식으로 데이터가 추가됨.
datas = {
    "name" : ["kim", "young"],
    "email" : ["kim@gmail.com", "young@naver.com"]
}
df = pd.DataFrame(datas)
df

name            email
0    kim    kim@gmail.com
1  young  young@naver.com

In [ ]:
# 데이터 프레임 생성 2 : 리스트의 딕셔너리

In [101]:
datas = [
    {"name" : "kim", "email" : "kim@gmail.com"},
    {"name" : "young", "email" : "young@gmail.com"},
]
df = pd.DataFrame(datas)
df

name            email
0    kim    kim@gmail.com
1  young  young@gmail.com

In [102]:
# 인덱스를 추가하는 방법
df = pd.DataFrame(datas, index=["one", "two"])
df

name            email
one    kim    kim@gmail.com
two  young  young@gmail.com

In [114]:
df.index = [1, 2]
df

name            email
1    kim    kim@gmail.com
2  young  young@gmail.com

In [ ]:
# 데이터 프레임에서 데이터의 선택 : row, column, (row, column)

In [132]:
df = pd.DataFrame(datas)
df

name            email
0    kim    kim@gmail.com
1  young  young@gmail.com

In [134]:
# row선택
df.loc[1]["name"]

'young'

In [ ]:
# index가 있으면 수정, 없으면 추가

In [136]:
df.loc[1][1] = "young@daum.com"
df.loc[2] = {"name" : "andy", "email" : "andy@naver.com"}
df

name           email
0    kim   kim@gmail.com
1  young  young@daum.com
2   andy  andy@naver.com

In [149]:
#칼럼 선택
email = df["email"]
email

0     kim@gmail.com
1    young@daum.com
2    andy@naver.com
Name: email, dtype: object

In [150]:
df["id"] = ""
df

name           email id
0    kim   kim@gmail.com   
1  young  young@daum.com   
2   andy  andy@naver.com

In [151]:
df["id"] = range(1,4)
df

name           email  id
0    kim   kim@gmail.com   1
1  young  young@daum.com   2
2   andy  andy@naver.com   3

In [152]:
df.dtypes

name     object
email    object
id        int32
dtype: object

In [153]:
# 로우, 칼럼 선택 리스트 추출

df.loc[[0, 2],["id", "name"]]

id  name
0   1   kim
2   3  andy

In [208]:
df.iloc[:2]

name           email  id
0    kim   kim@gmail.com   1
1  young  young@daum.com   2

In [161]:
#DtaFrame[ [칼럼명 순서] ] 재배치
dt = df[["id", "name","email"]]
dt

id   name           email
0   1    kim   kim@gmail.com
1   2  young  young@daum.com
2   3   andy  andy@naver.com

In [162]:
df

name           email  id
0    kim   kim@gmail.com   1
1  young  young@daum.com   2
2   andy  andy@naver.com   3

In [171]:
arr = np.array([1, 2, 3])
print(type(arr))

<class 'numpy.ndarray'>


In [179]:
arr2 = np.random.randint(4, 14, size=(3, 3))
arr2

array([[12,  5, 13],
       [11, 10,  9],
       [13,  6,  6]])

In [184]:
arr2[arr2 > 7]

array([12, 13, 11, 10,  9, 13])

In [206]:
np.random.rand(2, 3)

array([[0.0346786 , 0.16099664, 0.6332257 ],
       [0.0482832 , 0.89344077, 0.34983952]])